project:
  type: website
  output-dir: docs

website:
  title: "sains-data-2023"
  sidebar:
    contents: main-module/*
    

  navbar:
    right: 
      - icon: github
        href: https://github.com/carlesoctav/sains-data-2023
      

format:
  html:
    theme: litera
    css: styles.css
    toc: true



