project:
  type: website
  output-dir: docs

website:
  title: "sains-data-2023"
  sidebar:
    - section: main-module.qmd
      contents: main-module/*

format:
  html:
    theme: litera
    css: styles.css
    toc: true



